[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
serde = { workspace = true }

# Web only
gloo-net = { workspace = true, optional = true }

[features]
server = []
web = ["dep:gloo-net"]
