# fly.toml app configuration file generated for docsite-playground on 2025-02-04T15:44:00-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docsite-playground'
primary_region = 'lax'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
