[package]
name = "mdbook-gen"
version = "0.0.0"
edition = "2021"

[dependencies]
proc-macro2 = { version = "1.0" }
quote = "1.0"
syn = "2.0"
mdbook-shared = { path = "../mdbook-shared" }
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
macro_state = "0.2.0"
convert_case = "0.6.0"
postcard = { version = "1.0.4", features = ["use-std"] }
pulldown-cmark = "0.9.3"
syntect = "5.0"
dioxus-rsx = { version = "0.6.0-alpha.2" }
dioxus-autofmt = { version = "0.6.0-alpha.2" }
