# This excludes the template from the rest of the workspaces.
[workspace]

[package]
name = "playground-9a835e37-6bd6-48ae-9253-d832668029db"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5", features = ["web"] }