[application]
name = "9a835e37-6bd6-48ae-9253-d832668029db"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"
hot_reload = false

[web.app]
title = "Dioxus Playground"

####
#
# This is the only thing we need to change for built projects.
#
###
base_path = "./built/9a835e37-6bd6-48ae-9253-d832668029db"

[web.watcher]
index_on_404 = true
watch_path = ["src", "examples"]
[web.resource]
style = []
script = []
[web.resource.dev]
script = []
[application.plugins]
available = true
required = []

