[application]
name = "c5978c14-175b-4378-8bb1-4f6e6fc351c9"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"
hot_reload = false

[web.app]
title = "Dioxus Playground"

####
#
# This is the only thing we need to change for built projects.
#
###
base_path = "./built/c5978c14-175b-4378-8bb1-4f6e6fc351c9"

[web.watcher]
index_on_404 = true
watch_path = ["src", "examples"]
[web.resource]
style = []
script = []
[web.resource.dev]
script = []
[application.plugins]
available = true
required = []

