[package]
name = "example-projects"
version = "0.1.0"
edition = "2021"

[dependencies]
include_dir = "0.7.3"
once_cell = "1.17.1"
anyhow = "1.0.95"

model = { workspace = true }

[dev-dependencies]
dioxus = { workspace = true, features = ["web"] }
