# This excludes the template from the rest of the workspaces.
[workspace]

[package]
name = "play-57d2f289-ba45-3195-ae0a-ea089d2f9bf8"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { path = "../../../../../dioxus/packages/dioxus", features = ["web", "router", "launch", "logger", "lib"], default-features = false }
wasm-bindgen = "=0.2.100"

[profile.dev.package."*"]
opt-level = 3
debug = false
strip = true

[profile.dev.package.dioxus-devtools]
opt-level = 3
debug = true
strip = true

[profile.dev.package.dioxus-web]
opt-level = 3
debug = true
strip = true
