[application]
name = "5f1689ca-25e2-3fea-96d4-75ad3e26efa9"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"
hot_reload = false

[web.app]
base_path = "built/5f1689ca-25e2-3fea-96d4-75ad3e26efa9"

title = "Dioxus Playground"
[web.watcher]
index_on_404 = true
watch_path = ["src", "examples"]
[web.resource]
style = []
script = []
[web.resource.dev]
script = []
[application.plugins]
available = true
required = []
