[application]
name = "015cef34-f8d3-3b3f-913a-d74f0e3ac510"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"
hot_reload = false

[web.app]
base_path = "built/015cef34-f8d3-3b3f-913a-d74f0e3ac510"

title = "Dioxus Playground"
[web.watcher]
index_on_404 = true
watch_path = ["src", "examples"]
[web.resource]
style = []
script = []
[web.resource.dev]
script = []
[application.plugins]
available = true
required = []
