name: macOS tests

on:
  push:
    branches:
      - master
    paths:
      - mdbook-macro/src/**
      - mdbook-macro/Cargo.toml
      - mdbook-shared/src/**
      - mdbook-shared/Cargo.toml
      - syntect-html/src/**
      - syntect-html/Cargo.toml
      - use-mdbook/src/**
      - use-mdbook/Cargo.toml
      - example-book/**
      - .github/**
      - Cargo.toml

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
    paths:
      - mdbook-macro/src/**
      - mdbook-macro/Cargo.toml
      - mdbook-shared/src/**
      - mdbook-shared/Cargo.toml
      - syntect-html/src/**
      - syntect-html/Cargo.toml
      - use-mdbook/src/**
      - use-mdbook/Cargo.toml
      - example-book/**
      - .github/**
      - Cargo.toml

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Test Suite
    runs-on: macos-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v4
      - run: cargo test --all --tests
