[package]
name = "mdbook-gen-example"
version = "0.0.0"
edition = "2021"

[build-dependencies]
mdbook-gen = { path = "../mdbook-gen" }
mdbook-shared = { path = "../mdbook-shared" }
dioxus-autofmt = { version = "0.6.0-alpha.2" }
prettyplease = "0.2.20"
syn = "2.0"
