[package]
name = "mdbook-gen-example"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.163", features = ["derive"]}
use-mdbook = { workspace = true }
dioxus = { workspace = true, features = ["router"] }

[build-dependencies]
mdbook-gen = { path = "../mdbook-gen", features = ["manganis"] }
mdbook-shared = { path = "../mdbook-shared" }
dioxus-autofmt = { workspace = true }
prettyplease = "0.2.20"
syn = { workspace = true }
