[package]
name = "notion-to-blog"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
pulldown-cmark = { version = "0.13.0", default-features = false, features = ["simd"] }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
image = { version = "0.25", features = ["avif"] }
regex = "1.10"
walkdir = "2.5"
