# This excludes the template from the rest of the workspaces.
[workspace]

[package]
name = "playground-BUILD_ID"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5", features = ["web"] }

[profile.dev]
opt-level = 1