[package]
name = "searchable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { workspace = true, features = ["fullstack", "router"] }
dioxus-search = { workspace = true }
axum = { workspace = true, optional = true }
serde = { version = "1.0.174", features = ["derive"] }
getrandom = { workspace = true }
tokio = { version = "1.29.1", features = ["full"], optional = true }
log = "0.4.19"

[features]
web = ["getrandom/js", "dioxus/web"]
ssr = ["dioxus/server", "tokio", "axum"]
