# This excludes the template from the rest of the workspaces.
[workspace]

[package]
name = "play-{BUILD_ID}"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0-rc.0", features = ["web", "router"] }
wasm-bindgen = "=0.2.100"
web-sys = { version = "0.3", features = ["Location"] }

[profile.dev.package."*"]
opt-level = 3
debug = false
strip = true

[profile.dev.package.dioxus-devtools]
opt-level = 3
debug = true
strip = true

[profile.dev.package.dioxus-web]
opt-level = 3
debug = true
strip = true
