# This excludes the template from the rest of the workspaces.
[workspace]

[package]
name = "play-{BUILD_ID}"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "05c0980", features = ["web", "router"] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", rev = "2901fd2", version = "0.0.1", default-features = false, features = ["router"] }
time = { version = "0.3.44", features = ["std", "macros", "wasm-bindgen"] }
tracing = "0.1.41"
wasm-bindgen = "=0.2.100"
web-sys = { version = "0.3", features = ["Location"] }

[profile.dev.package."*"]
opt-level = 3
debug = false
strip = true

[profile.dev.package.dioxus-devtools]
opt-level = 3
debug = true
strip = true

[profile.dev.package.dioxus-web]
opt-level = 3
debug = true
strip = true

[patch.crates-io]
dioxus-dx-wire-format = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-core = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-logger = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-cli-config = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-signals = { git = "https://github.com/dioxuslabs/dioxus" }
subsecond = { git = "https://github.com/dioxuslabs/dioxus" }
subsecond-types = { git = "https://github.com/dioxuslabs/dioxus" }
generational-box = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-document = { git = "https://github.com/dioxuslabs/dioxus" }
