[package]
name = "docsrs-search"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus-search.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
zip = "4.3.0"
walkdir = "2"
tempdir = "0.3.7"
