[package]
name = "dioxus-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { workspace = true, features = ["web"] }
dioxus-logger = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
gloo-net = { workspace = true }

dioxus = { version = "0.5.1", features = ["web"] }
manganis = "0.2.2"
gloo-utils = "0.2.0"