[package]
name = "dioxus-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path = "../model" }
dioxus = { version = "0.5.1", features = ["web"] }
dioxus-logger = "0.5.1"
wasm-bindgen = "0.2.92"
web-sys = "0.3.69"
futures = "0.3.30"
manganis = "0.2.2"
#dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk", rev = "refs/pull/38/head", features = ["system_theme"] }
