[package]
name = "dioxus-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { workspace = true, features = ["web"] }
dioxus-logger = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
gloo-net = { workspace = true }

dioxus = { version = "0.6.0-alpha.2", features = ["web"] }
dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk", rev = "refs/pull/57/head", features = ["window_size", "timing"]}
gloo-utils = "0.2.0"
rsx-rosetta = "0.6.0-alpha.2"
dioxus-autofmt = "0.6.0-alpha.2"
wasm-bindgen = "0.2.93"
